"""add eligibility_overrides table

Revision ID: 1c926c759553
Revises: 1ec1b840f17a
Create Date: 2026-09-14 11:22:24.063318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c926c759553'
down_revision: Union[str, Sequence[str], None] = '1ec1b840f17a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eligibility_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usn', sa.String(length=16), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('exam', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usn'], ['students.usn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eligibility_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eligibility_overrides_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_eligibility_overrides_usn'), ['usn'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eligibility_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eligibility_overrides_usn'))
        batch_op.drop_index(batch_op.f('ix_eligibility_overrides_created_at'))

    op.drop_table('eligibility_overrides')
    # ### end Alembic commands ###
