"""v4 R1 baseline: rooms, availability, requests, conversations, traces, guard decisions

Revision ID: 1ec1b840f17a
Revises: 
Create Date: 2026-09-01 00:22:34.953517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec1b840f17a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('tier_history', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_owner'), ['owner'], unique=False)

    op.create_table('departments',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('intake', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('guard_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.String(length=36), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('actor_role', sa.String(length=16), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('reason_code', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('was_exposed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guard_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guard_decisions_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_decisions_capability'), ['capability'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_decisions_turn_id'), ['turn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_decisions_verdict'), ['verdict'], unique=False)

    op.create_table('intent_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('predicted_intent', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('expected_intent', sa.String(length=64), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usn', sa.String(length=16), nullable=True),
    sa.Column('audience_role', sa.String(length=16), nullable=True),
    sa.Column('dept_code', sa.String(length=8), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source_agent', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_usn'), ['usn'], unique=False)

    op.create_table('placement_drives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=False),
    sa.Column('package_lpa', sa.Float(), nullable=False),
    sa.Column('min_cgpa', sa.Float(), nullable=False),
    sa.Column('max_backlogs', sa.Integer(), nullable=False),
    sa.Column('min_attendance', sa.Float(), nullable=False),
    sa.Column('drive_date', sa.Date(), nullable=False),
    sa.Column('departments', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('requester', sa.String(length=64), nullable=False),
    sa.Column('subject_ref', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('reasons', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requests_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_requester'), ['requester'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_state'), ['state'], unique=False)

    op.create_table('rooms',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('room_type', sa.String(length=16), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('workflow_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('agent', sa.String(length=32), nullable=False),
    sa.Column('hop', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('elapsed_ms', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_events_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('conversation_turns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('resolved_entities', sa.Text(), nullable=False),
    sa.Column('pending_clarification', sa.Text(), nullable=True),
    sa.Column('pending_confirmation', sa.Text(), nullable=True),
    sa.Column('plan_state', sa.Text(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_turns_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('dept_code', sa.String(length=8), nullable=False),
    sa.Column('designation', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('qualified_subjects', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['dept_code'], ['departments.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faculty_dept_code'), ['dept_code'], unique=False)

    op.create_table('students',
    sa.Column('usn', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('dept_code', sa.String(length=8), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=4), nullable=False),
    sa.Column('cgpa', sa.Float(), nullable=False),
    sa.Column('backlogs', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('family_income', sa.Float(), nullable=False),
    sa.Column('admission_year', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dept_code'], ['departments.code'], ),
    sa.PrimaryKeyConstraint('usn')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_dept_code'), ['dept_code'], unique=False)

    op.create_table('subjects',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('dept_code', sa.String(length=8), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('block_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dept_code'], ['departments.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_dept_code'), ['dept_code'], unique=False)

    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usn', sa.String(length=16), nullable=False),
    sa.Column('subject_code', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_code'], ['subjects.code'], ),
    sa.ForeignKeyConstraint(['usn'], ['students.usn'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usn', 'subject_code', 'date', name='uq_attendance_entry')
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_records_usn'), ['usn'], unique=False)

    op.create_table('attendance_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usn', sa.String(length=16), nullable=False),
    sa.Column('subject_code', sa.String(length=16), nullable=False),
    sa.Column('classes_held', sa.Integer(), nullable=False),
    sa.Column('classes_attended', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('shortage', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_code'], ['subjects.code'], ),
    sa.ForeignKeyConstraint(['usn'], ['students.usn'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usn', 'subject_code', name='uq_attendance_summary')
    )
    with op.batch_alter_table('attendance_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_summary_usn'), ['usn'], unique=False)

    op.create_table('exam_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=16), nullable=False),
    sa.Column('dept_code', sa.String(length=8), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('session', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['subject_code'], ['subjects.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_schedules_dept_code'), ['dept_code'], unique=False)

    op.create_table('faculty_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_id', 'day', 'period', name='uq_faculty_unavailable')
    )
    with op.batch_alter_table('faculty_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faculty_availability_faculty_id'), ['faculty_id'], unique=False)

    op.create_table('fee_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usn', sa.String(length=16), nullable=False),
    sa.Column('fee_type', sa.String(length=32), nullable=False),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('fine', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['usn'], ['students.usn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fee_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_records_usn'), ['usn'], unique=False)

    op.create_table('hall_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usn', sa.String(length=16), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('reasons', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usn'], ['students.usn'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usn', 'semester', name='uq_hall_ticket')
    )
    with op.batch_alter_table('hall_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hall_tickets_usn'), ['usn'], unique=False)

    op.create_table('marks_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usn', sa.String(length=16), nullable=False),
    sa.Column('subject_code', sa.String(length=16), nullable=False),
    sa.Column('internal', sa.Integer(), nullable=False),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.Column('entered_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['subject_code'], ['subjects.code'], ),
    sa.ForeignKeyConstraint(['usn'], ['students.usn'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usn', 'subject_code', 'internal', name='uq_marks')
    )
    with op.batch_alter_table('marks_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marks_records_usn'), ['usn'], unique=False)

    op.create_table('placement_shortlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drive_id', sa.Integer(), nullable=False),
    sa.Column('usn', sa.String(length=16), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('reasons', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['placement_drives.id'], ),
    sa.ForeignKeyConstraint(['usn'], ['students.usn'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_id', 'usn', name='uq_shortlist_entry')
    )
    with op.batch_alter_table('placement_shortlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_placement_shortlists_usn'), ['usn'], unique=False)

    op.create_table('scholarship_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usn', sa.String(length=16), nullable=False),
    sa.Column('scheme', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reasons', sa.Text(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usn'], ['students.usn'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usn', 'scheme', name='uq_scholarship_scheme')
    )
    with op.batch_alter_table('scholarship_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scholarship_assessments_usn'), ['usn'], unique=False)

    op.create_table('teaching_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=16), nullable=False),
    sa.Column('dept_code', sa.String(length=8), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['subject_code'], ['subjects.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_code', 'dept_code', 'year', 'section', name='uq_teach')
    )
    with op.batch_alter_table('teaching_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teaching_assignments_faculty_id'), ['faculty_id'], unique=False)

    op.create_table('timetable_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dept_code', sa.String(length=8), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=4), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=16), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('room_code', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['room_code'], ['rooms.code'], ),
    sa.ForeignKeyConstraint(['subject_code'], ['subjects.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dept_code', 'year', 'section', 'day', 'period', name='uq_tt_slot')
    )
    with op.batch_alter_table('timetable_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timetable_slots_dept_code'), ['dept_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_timetable_slots_room_code'), ['room_code'], unique=False)

    op.create_table('trace_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.String(length=36), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=48), nullable=False),
    sa.Column('verdict', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['turn_id'], ['conversation_turns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trace_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trace_records_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_trace_records_turn_id'), ['turn_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('usn', sa.String(length=16), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('dept_code', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['dept_code'], ['departments.code'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['usn'], ['students.usn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('trace_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trace_records_turn_id'))
        batch_op.drop_index(batch_op.f('ix_trace_records_kind'))

    op.drop_table('trace_records')
    with op.batch_alter_table('timetable_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timetable_slots_room_code'))
        batch_op.drop_index(batch_op.f('ix_timetable_slots_dept_code'))

    op.drop_table('timetable_slots')
    with op.batch_alter_table('teaching_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teaching_assignments_faculty_id'))

    op.drop_table('teaching_assignments')
    with op.batch_alter_table('scholarship_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scholarship_assessments_usn'))

    op.drop_table('scholarship_assessments')
    with op.batch_alter_table('placement_shortlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_placement_shortlists_usn'))

    op.drop_table('placement_shortlists')
    with op.batch_alter_table('marks_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marks_records_usn'))

    op.drop_table('marks_records')
    with op.batch_alter_table('hall_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hall_tickets_usn'))

    op.drop_table('hall_tickets')
    with op.batch_alter_table('fee_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_records_usn'))

    op.drop_table('fee_records')
    with op.batch_alter_table('faculty_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faculty_availability_faculty_id'))

    op.drop_table('faculty_availability')
    with op.batch_alter_table('exam_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_schedules_dept_code'))

    op.drop_table('exam_schedules')
    with op.batch_alter_table('attendance_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_summary_usn'))

    op.drop_table('attendance_summary')
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_usn'))

    op.drop_table('attendance_records')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_dept_code'))

    op.drop_table('subjects')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_dept_code'))

    op.drop_table('students')
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faculty_dept_code'))

    op.drop_table('faculty')
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_turns_conversation_id'))

    op.drop_table('conversation_turns')
    with op.batch_alter_table('workflow_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_events_workflow_id'))

    op.drop_table('workflow_events')
    op.drop_table('rooms')
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requests_state'))
        batch_op.drop_index(batch_op.f('ix_requests_requester'))
        batch_op.drop_index(batch_op.f('ix_requests_kind'))

    op.drop_table('requests')
    op.drop_table('placement_drives')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_usn'))

    op.drop_table('notifications')
    op.drop_table('intent_logs')
    with op.batch_alter_table('guard_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guard_decisions_verdict'))
        batch_op.drop_index(batch_op.f('ix_guard_decisions_turn_id'))
        batch_op.drop_index(batch_op.f('ix_guard_decisions_capability'))
        batch_op.drop_index(batch_op.f('ix_guard_decisions_actor'))

    op.drop_table('guard_decisions')
    op.drop_table('departments')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_owner'))

    op.drop_table('conversations')
    # ### end Alembic commands ###
