import { Navigate, Outlet, Route, Routes, useLocation } from 'react-router-dom'
import { useAuth } from './auth'
import { AppShell, LoadingScreen } from './components'
import { LoginPage, StudentDashboard, FacultyConsole, HODAnalytics, PrincipalAnalytics, AdminAdmissions, TimetablePage, AssistantPage, WorkflowsPage, SystemStatusPage } from './pages'
import type { Role } from './types'

function Protected({ role }: { role?: Role }) { const { user, loading } = useAuth(); const location = useLocation(); if (loading) return <LoadingScreen />; if (!user) return <Navigate to="/login" state={{ from: location }} replace />; if (role && user.role !== role && !(user.role === 'admin' || (user.role === 'principal' && role === 'hod'))) return <Navigate to={`/${user.role}`} replace />; return <Outlet /> }
function HomeRedirect() { const { user } = useAuth(); return <Navigate to={user ? `/${user.role}` : '/login'} replace /> }
export default function App() { return <Routes><Route path="/login" element={<LoginPage />} /><Route element={<Protected />}><Route element={<AppShell />}><Route index element={<HomeRedirect />} /><Route path="student" element={<Protected role="student" />}><Route index element={<StudentDashboard />} /><Route path="timetable" element={<TimetablePage />} /></Route><Route path="faculty" element={<Protected role="faculty" />}><Route index element={<FacultyConsole />} /><Route path="timetable" element={<TimetablePage />} /></Route><Route path="hod" element={<Protected role="hod" />}><Route index element={<HODAnalytics />} /><Route path="timetable" element={<TimetablePage />} /></Route><Route path="principal" element={<Protected role="principal" />}><Route index element={<PrincipalAnalytics />} /><Route path="admissions" element={<AdminAdmissions />} /><Route path="timetable" element={<TimetablePage />} /></Route><Route path="admin" element={<Protected role="admin" />}><Route index element={<AdminAdmissions />} /><Route path="timetable" element={<TimetablePage />} /></Route><Route path="assistant" element={<AssistantPage />} /><Route path="workflows" element={<WorkflowsPage />} /><Route path="system" element={<SystemStatusPage />} /></Route></Route><Route path="*" element={<HomeRedirect />} /></Routes> }
