import { useState, type ReactNode } from 'react'
import { NavLink, Outlet, useNavigate } from 'react-router-dom'
import { Activity, Bot, CalendarDays, ChevronRight, GraduationCap, LayoutDashboard, LogOut, Menu, PanelLeftClose, PanelLeftOpen, Settings2, ShieldCheck, Workflow, X } from 'lucide-react'
import { useAuth, roleLabel } from './auth'

export function LoadingScreen() { return <div className="loading-screen"><div className="loader" /><span>Loading MAWOS workspace</span></div> }
export function PageLoader() { return <div className="page-loader"><div className="loader" /> Syncing institutional data...</div> }
export function ErrorState({ message = 'Unable to load this view.' }: { message?: string }) { return <div className="empty-state error-state"><strong>Could not load data</strong><span>{message}</span></div> }
export function EmptyState({ title, detail }: { title: string; detail: string }) { return <div className="empty-state"><strong>{title}</strong><span>{detail}</span></div> }
export function Badge({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'good' | 'warn' | 'bad' | 'info' | 'neutral' }) { return <span className={`badge badge-${tone}`}>{children}</span> }
export function StatCard({ label, value, detail, tone = '' }: { label: string; value: ReactNode; detail?: string; tone?: string }) { return <section className="stat-card"><div className="stat-label">{label}</div><div className={`stat-value ${tone}`}>{value}</div>{detail && <div className="stat-detail">{detail}</div>}</section> }
export function Section({ title, eyebrow, action, children, className = '' }: { title: string; eyebrow?: string; action?: ReactNode; children: ReactNode; className?: string }) { return <section className={`panel ${className}`}><div className="panel-heading"><div><h2>{title}</h2>{eyebrow && <p>{eyebrow}</p>}</div>{action}</div>{children}</section> }
export function PanelMessage({ children, tone = 'info' }: { children: ReactNode; tone?: string }) { return <div className={`panel-message ${tone}`}>{children}</div> }
export function Button({ children, variant = 'primary', type = 'button', disabled, onClick, title }: { children: ReactNode; variant?: 'primary' | 'secondary' | 'quiet' | 'danger'; type?: 'button' | 'submit'; disabled?: boolean; onClick?: () => void; title?: string }) { return <button className={`button button-${variant}`} type={type} disabled={disabled} onClick={onClick} title={title}>{children}</button> }
export function DataTable({ children }: { children: ReactNode }) { return <div className="table-wrap"><table>{children}</table></div> }
export function FormatMoney({ value }: { value: number }) { return <>₹{Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 0 })}</> }

const navFor = (role: string) => {
  const base = `/${role}`
  const items = [{ to: base, label: 'Overview', icon: LayoutDashboard }]
  if (role === 'student' || role === 'faculty' || role === 'hod' || role === 'principal' || role === 'admin') items.push({ to: `${base}/timetable`, label: 'Timetable', icon: CalendarDays })
  if (role === 'principal' || role === 'admin') items.push({ to: `${base}/admissions`, label: 'Admissions', icon: GraduationCap })
  items.push({ to: '/workflows', label: 'Workflow traces', icon: Workflow }, { to: '/assistant', label: 'AI assistant', icon: Bot })
  if (role === 'admin' || role === 'principal') items.push({ to: '/system', label: 'System status', icon: Activity })
  return items
}

function Sidebar({ collapsed, onClose }: { collapsed: boolean; onClose: () => void }) { const { user } = useAuth(); const navigate = useNavigate(); const items = navFor(user?.role || 'student'); return <aside className={`sidebar ${collapsed ? 'collapsed' : ''}`}><div className="brand"><div className="brand-mark">M</div><div className="brand-copy"><strong>MAWOS</strong><span>Institutional operations</span></div><button className="icon-button mobile-only" onClick={onClose} aria-label="Close navigation"><X size={18} /></button></div><div className="sidebar-context"><div className="context-kicker">Current workspace</div><strong>{roleLabel(user?.role)}</strong><span>{user?.dept || 'Institution-wide'} scope</span></div><nav className="sidebar-nav">{items.map(({ to, label, icon: Icon }, index) => <NavLink key={`${label}-${index}`} to={to} end={to === `/${user?.role}`} onClick={onClose} className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}><Icon size={18} /><span>{label}</span>{label === 'AI assistant' && <span className="nav-dot" />}</NavLink>)}</nav><div className="sidebar-foot"><div className="research-mark"><ShieldCheck size={16} /><span>Research mode enabled</span></div><button className="nav-item" onClick={() => navigate('/system')}><Settings2 size={18} /><span>Environment</span></button></div></aside> }

export function AppShell() { const { user, logout } = useAuth(); const [mobileOpen, setMobileOpen] = useState(false); const [collapsed, setCollapsed] = useState(false); return <div className="app-shell"><div className={`sidebar-backdrop ${mobileOpen ? 'visible' : ''}`} onClick={() => setMobileOpen(false)} /><div className={`sidebar-wrap ${mobileOpen ? 'open' : ''}`}><Sidebar collapsed={collapsed} onClose={() => setMobileOpen(false)} /></div><div className={`app-main ${collapsed ? 'sidebar-collapsed' : ''}`}><header className="topbar"><button className="icon-button mobile-only" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Menu size={20} /></button><button className="icon-button desktop-only" onClick={() => setCollapsed(!collapsed)} aria-label="Toggle navigation width">{collapsed ? <PanelLeftOpen size={19} /> : <PanelLeftClose size={19} />}</button><div className="crumbs"><span>MAWOS</span><ChevronRight size={14} /><strong>{roleLabel(user?.role)} workspace</strong></div><div className="topbar-right"><Badge tone={user?.ai_mode === 'llm' ? 'good' : 'neutral'}><span className="status-dot" />{user?.ai_mode === 'llm' ? 'LLM online' : 'Fallback AI'}</Badge><div className="profile-chip"><div className="avatar">{user?.name?.slice(0, 1).toUpperCase()}</div><div><strong>{user?.name}</strong><span>{user?.username}</span></div></div><button className="icon-button" onClick={logout} aria-label="Log out" title="Log out"><LogOut size={18} /></button></div></header><main className="content"><Outlet /></main><footer className="app-footer">MAWOS multi-agent institutional operations system <span>•</span> v2.0</footer></div></div> }
